baseURL = 'https://www.nonmachinepeople.net/'
languageCode = 'en-gb'
title = 'non-machine people'
buildDrafts = true
enableGitInfo = true

[markup.goldmark.extensions.extras.superscript]
enable = true

[module]
[[module.imports]]
path = "github.com/tnarik/web-blog.nonmachinepeople.net-theme"
disable = false

[languages]
[languages.en]
disabled = false
languageCode = 'en-GB'
languageDirection = 'ltr'
languageName = 'English'
# title = ''
weight = 0
[languages.es]
disabled = false
languageCode = 'es-ES'
languageDirection = 'ltr'
languageName = 'Spanish'
# title = ''
weight = 1

[params]
mainSections = ['posts']
ShowReadingTime = true

[taxonomies]
category = "categories"
tags = "tags"
series = "series"

[menu]
[[menu.main]]
identifier = 'posts'
name = 'posts'
pageRef = '/posts'
weight = 2
[[menu.main]]
identifier = 'adventures'
name = 'adventures'
pageRef = '/adventures'
weight = 1
[[menu.main]]
identifier = 'search'
name = ' '
post = '<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>'
pageRef = '/search'
weight = 10

# Enable searching via PaperMod, using Fuse.js
[outputs]
home = [ "HTML", "RSS", "JSON" ]