baseURL = 'https://www.nonmachinepeople.net/'
languageCode = 'en-gb'
title = 'non-machine people'
buildDrafts = true

[module]
[[module.imports]]
path = "github.com/tnarik/web-blog.nonmachinepeople.net-theme"
disable = false

[languages]
[languages.en]
disabled = false
languageCode = 'en-GB'
languageDirection = 'ltr'
languageName = 'English'
# title = ''
weight = 0
[languages.es]
disabled = false
languageCode = 'es-ES'
languageDirection = 'ltr'
languageName = 'Spanish'
# title = ''
weight = 1

[params]
mainSections = ['post']

[taxonomies]
category = "categories"
tags = "tags"
series = "series"

[menu]
[[menu.main]]
name = 'posts'
pageRef = '/post'
[[menu.main]]
name = 'adventures'
pageRef = '/adventure'
